import {matchupReport} from '../../lib/matchup';
import {forecast,isHeld,type LeaguePlayer,type Snapshot} from '../../lib/football';
import {managerLabel,teamActivity,activityText,teamNews} from '../../lib/league-intel';
import {PlayerPhoto} from './PlayerPhoto';
const pts=(n:number|null)=>n===null?'Unavailable':n.toFixed(1);
export function MatchupScreen({snapshot:s,onPlayer,onLineup,onWaivers,onOpponent}:{snapshot:Snapshot;onPlayer:(p:LeaguePlayer)=>void;onLineup:()=>void;onWaivers:()=>void;onOpponent:()=>void}) {
  const r=matchupReport(s);
  if(!r)return <section className="ge-card gm-empty"><h2>No matchup assigned</h2><p>ESPN has not returned an opponent for this scoring week. Your roster and available player tools still work.</p><button className="ge-button" onClick={onLineup}>Review my lineup</button></section>;
  const mine=s.teams.find(t=>t.id===s.teamId),moves=teamActivity(s,r.opponent.id).slice(0,3),news=teamNews(s,r.opponent.id).slice(0,2);
  const title=r.gap===null?'The picture is incomplete':Math.abs(r.gap)<3?'This looks close':r.gap>0?'You have the projected edge':'There is ground to make up';
  const cell=(p:LeaguePlayer|undefined)=>p?<button className="gm-player" onClick={()=>onPlayer(p)}><PlayerPhoto player={p}/><span><strong>{p.name}</strong><small>{p.position} · {p.proTeam}{p.opponent?` vs ${p.opponent}`:''}</small><small>{p.bye?'Bye: no game':p.status==='ACTIVE'?'No injury flag':p.status.replaceAll('_',' ')} · {isHeld(p)?'Locked or timing unconfirmed':'Can still change'}</small></span><b>{pts(forecast(p).points)}<small>est. pts</small></b></button>:<p className="gm-vacancy">Empty starting slot</p>;
  return <div className="gm-screen">
    <section className="gm-hero" aria-label="Matchup scoreboard">
      <div className="gm-hero-label"><span>WEEK {s.week} MATCHUP</span><span>{s.scoring}</span></div>
      <div className="gm-scoreboard">
        <div><span>YOUR TEAM</span><h2>{mine?.name??s.teamName}</h2><p>{managerLabel(mine)}</p><strong>{pts(r.score)}</strong><small>ESPN score</small></div>
        <span className="gm-vs">VS</span>
        <div><span>YOUR OPPONENT</span><h2>{r.opponent.name}</h2><p>{managerLabel(r.opponent)}</p><strong>{pts(r.opponentScore)}</strong><small>ESPN score</small></div>
      </div>
      <p className="gm-score-note">Scores as of {new Date(s.acquiredAt).toLocaleString()}. {r.match.endWeek!==r.match.week?`This matchup spans weeks ${r.match.week}–${r.match.endWeek}; estimates below cover week ${s.week} only.`:'Scores may lag ESPN. Weekly estimates below are separate from points already scored.'}</p>
    </section>
    <section className="ge-card gm-outlook"><span className="ge-eyebrow">HOW IT LOOKS</span><h2>{title}</h2>
      <div className="gm-estimates"><div><span>Your weekly estimate</span><strong>{pts(r.own.points)}{r.own.missing?' (partial)':''}</strong></div><div><span>Their weekly estimate</span><strong>{pts(r.other.points)}{r.other.missing?' (partial)':''}</strong></div><div><span>Estimated difference</span><strong>{r.gap===null?'Not enough data':`${r.gap>=0?'+':''}${r.gap.toFixed(1)} for you`}</strong></div></div>
      <p>{r.gap===null?'Missing slots or player estimates prevent a complete comparison.':r.gap>=0?'Protect the points you have: resolve lineup flags and confirm availability before kickoff.':'Start with the bench changes below. A tough matchup alone is not a reason to drop a useful player.'}</p>
      <details><summary>What these numbers mean</summary><p>Full-week estimates use your league scoring, ESPN projections and recent player history. They are not a live final-score forecast, remaining points or a win probability. Actual points are not added to these estimates. Empty slots or unavailable estimates make totals partial.</p></details>
    </section>
    <div className="gm-insights">
      <section className="ge-card gm-panel"><span className="ge-eyebrow">YOUR NEXT MOVE</span><h2>{r.gain!==null&&r.gain>=.5?`Find ${r.gain.toFixed(1)} more points on your bench`:r.gain===null?'Check incomplete lineup data':'No clear bench upgrade right now'}</h2>
        {r.gain!==null&&r.gain>=.5?<><p>These changes work together as one lineup plan. The gain is for the whole plan, not each swap.</p><ul>{r.changes.map(c=><li key={c.slot.id}><strong>{c.slot.label}: start {c.incoming.name}</strong><br/>Instead of {c.outgoing?.name??'an empty slot'}.</li>)}</ul></>:<p>{r.gain===null?'We cannot quantify an improvement until the missing estimates are available.':'Your available bench does not produce a meaningful improvement in the current model. Check flagged players before making a move.'}</p>}
        <div className="ge-actions"><button className="ge-button" onClick={onLineup}>Review lineup plan</button><button className="ge-button secondary" onClick={onWaivers}>Check available players</button></div><p className="ge-footnote">{r.open} of your starters can still be changed. Kickoff locks and position eligibility are respected. Confirm moves in ESPN.</p>
      </section>
      <section className="ge-card gm-panel"><span className="ge-eyebrow">DON’T UNDERESTIMATE THEM</span><h2>{r.theirGain!==null&&r.theirGain>=.5?`They could add ${r.theirGain.toFixed(1)} points from their bench`:'Watch their next move'}</h2><p>{r.theirGain===null?'Their available data is incomplete, so a bench improvement cannot be calculated.':r.theirGain>=.5?'Their current lineup may understate their strength. That estimate assumes they make their best available bench changes.':'No clear bench upgrade is supported by the available estimates. They can still make pickups or trades.'}</p><p>{r.theirOpen} of their starters can still be changed.</p><button className="ge-button secondary" onClick={onOpponent}>Opponent news & moves</button></section>
    </div>
    <div className="gm-insights">
      <section className="ge-card gm-panel"><h2>Where you have an edge</h2>{r.strengths.length?r.strengths.map(x=><p key={x.slot.id}><strong>{x.ours?.name} · {x.slot.label}</strong><br/>Estimated {x.gap!.toFixed(1)} points above {x.theirs?.name} in the same fantasy slot.</p>):<p>No clear slot advantage in the available estimates.</p>}</section>
      <section className="ge-card gm-panel"><h2>Where they can hurt you</h2>{r.weaknesses.length?r.weaknesses.map(x=><p key={x.slot.id}><strong>{x.theirs?.name} · {x.slot.label}</strong><br/>Estimated {Math.abs(x.gap!).toFixed(1)} points above {x.ours?.name} in the same fantasy slot.</p>):<p>No clear opposing slot advantage in the available estimates.</p>}<p className="ge-footnote">Slot comparisons help explain the gap. Players face their own NFL opponents, not each other.</p></section>
    </div>
    <section className="ge-card gm-panel"><h2>Availability watch</h2><div className="gm-insights">{[{title:'Your starters',players:r.ownFlags},{title:'Their starters',players:r.theirFlags}].map(x=><div key={x.title}><h3>{x.title}</h3>{x.players.length?x.players.map(p=><div key={p.id}>{cell(p)}</div>):<p>No injury or bye flags reported for these starters.</p>}</div>)}</div><p className="ge-footnote">An injury flag does not confirm a player will miss the game. Opponents can replace unavailable starters. This is not an automatic scoring bonus.</p></section>
    <section className="ge-card gm-panel"><div className="ge-card-head"><h2>Every starter, side by side</h2><span className="ge-footnote">Tap a player for details</span></div><div className="gm-lineup-head"><strong>Your team</strong><strong>{r.opponent.name}</strong></div>{r.rows.map(x=><div className="gm-slot" key={x.slot.id}><div className="gm-slot-title"><strong>{x.slot.label}</strong><span>{x.gap===null?'Comparison incomplete':Math.abs(x.gap)<.5?'About even':`${Math.abs(x.gap).toFixed(1)} point edge: ${x.gap>0?'you':'them'}`}</span></div><div className="gm-lineup-pair"><div><small className="gm-mobile-label">You</small>{cell(x.ours)}</div><div><small className="gm-mobile-label">Opponent</small>{cell(x.theirs)}</div></div></div>)}</section>
    <section className="ge-card gm-panel"><h2>What changed on their side</h2>{moves.length?moves.map(m=><p key={m.id}><strong>{activityText(m,s)}</strong><br/>{m.source==='espn'?'Confirmed by ESPN':'Observed between refreshes'} · {new Date(m.at).toLocaleString()}</p>):<p>No saved roster moves to show yet.</p>}{news.map(n=><p key={n.article.id}><a href={n.article.url} target="_blank" rel="noreferrer">{n.article.headline}</a><br/><small>{n.direct?'Player news':'NFL team context, not necessarily about their starter'}</small></p>)}<button className="ge-link" onClick={onOpponent}>See all opponent updates</button></section>
  </div>;
}
