/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGridironWorkspaceRouteImport } from './routes/api/gridiron/workspace'
import { Route as ApiGridironStatusRouteImport } from './routes/api/gridiron/status'
import { Route as ApiGridironContextRouteImport } from './routes/api/gridiron/context'
import { Route as ApiGridironConnectionRouteImport } from './routes/api/gridiron/connection'
import { Route as ApiGridironAdvisorRouteImport } from './routes/api/gridiron/advisor'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGridironWorkspaceRoute = ApiGridironWorkspaceRouteImport.update({
  id: '/api/gridiron/workspace',
  path: '/api/gridiron/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGridironStatusRoute = ApiGridironStatusRouteImport.update({
  id: '/api/gridiron/status',
  path: '/api/gridiron/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGridironContextRoute = ApiGridironContextRouteImport.update({
  id: '/api/gridiron/context',
  path: '/api/gridiron/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGridironConnectionRoute = ApiGridironConnectionRouteImport.update({
  id: '/api/gridiron/connection',
  path: '/api/gridiron/connection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGridironAdvisorRoute = ApiGridironAdvisorRouteImport.update({
  id: '/api/gridiron/advisor',
  path: '/api/gridiron/advisor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/connections': typeof ConnectionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/gridiron/advisor': typeof ApiGridironAdvisorRoute
  '/api/gridiron/connection': typeof ApiGridironConnectionRoute
  '/api/gridiron/context': typeof ApiGridironContextRoute
  '/api/gridiron/status': typeof ApiGridironStatusRoute
  '/api/gridiron/workspace': typeof ApiGridironWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/connections': typeof ConnectionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/gridiron/advisor': typeof ApiGridironAdvisorRoute
  '/api/gridiron/connection': typeof ApiGridironConnectionRoute
  '/api/gridiron/context': typeof ApiGridironContextRoute
  '/api/gridiron/status': typeof ApiGridironStatusRoute
  '/api/gridiron/workspace': typeof ApiGridironWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/connections': typeof ConnectionsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/gridiron/advisor': typeof ApiGridironAdvisorRoute
  '/api/gridiron/connection': typeof ApiGridironConnectionRoute
  '/api/gridiron/context': typeof ApiGridironContextRoute
  '/api/gridiron/status': typeof ApiGridironStatusRoute
  '/api/gridiron/workspace': typeof ApiGridironWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/connections'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/gridiron/advisor'
    | '/api/gridiron/connection'
    | '/api/gridiron/context'
    | '/api/gridiron/status'
    | '/api/gridiron/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/connections'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/gridiron/advisor'
    | '/api/gridiron/connection'
    | '/api/gridiron/context'
    | '/api/gridiron/status'
    | '/api/gridiron/workspace'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/connections'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/gridiron/advisor'
    | '/api/gridiron/connection'
    | '/api/gridiron/context'
    | '/api/gridiron/status'
    | '/api/gridiron/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ConnectionsRoute: typeof ConnectionsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiGridironAdvisorRoute: typeof ApiGridironAdvisorRoute
  ApiGridironConnectionRoute: typeof ApiGridironConnectionRoute
  ApiGridironContextRoute: typeof ApiGridironContextRoute
  ApiGridironStatusRoute: typeof ApiGridironStatusRoute
  ApiGridironWorkspaceRoute: typeof ApiGridironWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gridiron/workspace': {
      id: '/api/gridiron/workspace'
      path: '/api/gridiron/workspace'
      fullPath: '/api/gridiron/workspace'
      preLoaderRoute: typeof ApiGridironWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gridiron/status': {
      id: '/api/gridiron/status'
      path: '/api/gridiron/status'
      fullPath: '/api/gridiron/status'
      preLoaderRoute: typeof ApiGridironStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gridiron/context': {
      id: '/api/gridiron/context'
      path: '/api/gridiron/context'
      fullPath: '/api/gridiron/context'
      preLoaderRoute: typeof ApiGridironContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gridiron/connection': {
      id: '/api/gridiron/connection'
      path: '/api/gridiron/connection'
      fullPath: '/api/gridiron/connection'
      preLoaderRoute: typeof ApiGridironConnectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gridiron/advisor': {
      id: '/api/gridiron/advisor'
      path: '/api/gridiron/advisor'
      fullPath: '/api/gridiron/advisor'
      preLoaderRoute: typeof ApiGridironAdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ConnectionsRoute: ConnectionsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiGridironAdvisorRoute: ApiGridironAdvisorRoute,
  ApiGridironConnectionRoute: ApiGridironConnectionRoute,
  ApiGridironContextRoute: ApiGridironContextRoute,
  ApiGridironStatusRoute: ApiGridironStatusRoute,
  ApiGridironWorkspaceRoute: ApiGridironWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
